### ISSUE TITLE
SIGSEGV if communication is closed by server

### ISSUE THREAD

**Issue by SAmeis** [Warfley/LazWebsockets#10]
The websocket server crashes with SIGSEGV when a connection shut down is initiated at server side:

Edit the chatServer.pas example to use this method:
```pascal
  procedure TSocketHandler.DoHandleCommunication(
    ACommunication: TWebsocketCommunincator);
  begin
    WriteLn('Connected to ', ACommunication.SocketStream.RemoteAddress.Address);
    ACommunication.OnRecieveMessage := @MessageRecieved;
    ACommunication.OnClose := @ConnectionClosed;
    // leave method to shut down connection
  end; 
```

Then do the following:

1. Start server
2. Connect with client (I used websocat) - the server will close the connection immediately but dosn't crash
3. Connect with client - the SIGSEGV is raised in wsstream TLockedSocketStream.LockRead when locking the critical section

**Comment by Warfley** [comment]
Turned out to be a race condition, fixed it by simply waiting a bit
