### ISSUE TITLE
Same Port for Webserver and Websocket

### ISSUE THREAD

**Issue by PeterKainz** [Warfley/LazWebsockets#11]
Hi guys,

not an issue, just a question!
is it possible to use the same port for webserver and websocket (upgrade)? And if, a small exampl would be nice

I want to run a small webserver witch delivers just a index.html with javascript code witch opens a websocket connection to the same port like the webserver, i did it with node.js and its easy, but i want to use lazarus and LazWebsockets

thanks in advance
peter

**Comment by Warfley** [comment]
Short answer, no

Reason: this is a small websocket implementation. Also implementing an HTTP server would require at least twice the effort (if not much more), while there are already great HTTP server components available (FPWeb, Indy, etc.).

But, I highly recommend using a reverse proxy anyway (for example using nginx), as this has a lot of advantages. As a side product, in that reverse proxy you can then dispatch different paths to different internal ports, meaning from the outside it looks like everything is running on the same port, while nginx divides requests into the different streams.
