### ISSUE TITLE
100% CPU load with AcceptingMethod = samThreadPool

### ISSUE THREAD

**Issue by SAmeis** [Warfley/LazWebsockets#13]
When setting AcceptingMethod to samThreadPool, one thread runs with 100 % cpu load.

1. Start websocket server with AcceptingMethod = samThreadPool; now the CPU load is low
2. Connect with a client. Now the CPU load increases and stays at 100% for one thread

Changing AcceptingMethod to samThreaded recuces the CPU load after connection significantly.

**Comment by Warfley** [comment]
I rewrote the thread pooling code, now this should not make any problems anymore. Also you can deactivate thread pooling if there are any other issues (see Readme for further information)
