### ISSUE TITLE
TWebSocketServer.Destroy raises exception

### ISSUE THREAD

**Issue by TetrisSQC** [Warfley/LazWebsockets#15]
If you run the Server in a separate thread like 
```
  TWebSocketThread = class(TThread)
  protected
    FSocket: TWebSocketServer;
    procedure Execute; override;
  public
    constructor Create(const APort: integer);
    destructor Destroy; override;
  end;  

constructor TWebSocketThread.Create(const APort: integer);
begin
  inherited create(false);
  FSocket := TWebSocketServer.Create(APort);
  FSocket.FreeHandlers := True;
  FSocket.RegisterHandler('*', '*', TSocketHandler.Create(FSocket), True, True);
end;

destructor TWebSocketThread.Destroy;
begin
  FSocket.Free;
  Terminate;
  WaitFor;
  inherited;
end;

procedure TWebSocketThread.Execute;
begin
  FSocket.Start;
end;  
```

Your Destructor raises an exception.
The solution is to free the FHostMap before the Socket like this:

```
destructor TWebSocketServer.Destroy;
begin
  Stop(True);
  FHostMap.Free;
  FSocket.Free;
  inherited Destroy;
end;
```

Regards
Christian

**Comment by Warfley** [comment]
Hey, thank you
If you mean the "Could not accept a client connection on socket: -1, error 1004" exception, this exception is completely expected at this point, and a behavior of the FCLs ssocket unit.

But I can also not reproduce that this exception does not occur when swapping the two lines. If you get another exception, please provide the error type and message es well as the error code (if it is an ESocketError).

Also it would be quite useful to know which OS you are using.

Also, these two lines don't really depend on oneanother, so I doubt that it has anything to do with the Freeing order. You could try putting a Sleep(100) or so after the Close call, to test if it might just be a race condition

With best regards,
Frederic

**Comment by TetrisSQC** [comment]
Thanks, 

yes you are probably right. 

`unit uatscwebsocket;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, wsutils, wsmessages, wsstream, WebSocketServer;

type
  TMyWebSocketServer = class;

  TSocketHandler = class(TThreadedWebsocketHandler)
  private
    FParent: TMyWebSocketServer;
    procedure MessageReceived(Sender: TObject);
  public
    constructor Create(const AParent: TMyWebSocketServer);
    function Accept(const ARequest: TRequestData;
      const ResponseHeaders: TStrings): boolean; override;
    procedure DoHandleCommunication(ACommunication: TWebsocketCommunicator);
      override;
  end;

  TOnResponse = procedure(Sender: TObject; const ARequest: String; out AResponse: String) of object;

  TMyWebSocketServer = class(TThread)
  protected
    FSocket: TWebSocketServer;
    FOnResponse: TOnResponse;
    procedure Execute; override;
  public
    constructor Create(const APort: integer);
    destructor Destroy; override;

    property OnResponse: TOnResponse read FOnResponse write FOnResponse;
  end;

implementation


{ TSocketHandler }
constructor TSocketHandler.Create(const AParent: TMyWebSocketServer);
begin
  inherited Create;
  FParent := AParent;
end;

function TSocketHandler.Accept(const ARequest: TRequestData;
  const ResponseHeaders: TStrings): boolean;
begin
  Result := True;
end;

procedure TSocketHandler.DoHandleCommunication(ACommunication: TWebsocketCommunicator);
begin
  ACommunication.OnReceiveMessage := @MessageReceived;
  while ACommunication.Open do
  begin
    Sleep(10);
    if FParent.Terminated then
      break;
  end;
end;

procedure TSocketHandler.MessageReceived(Sender: TObject);
var
  Messages: TWebsocketMessageOwnerList;
  m: TWebsocketMessage;
  Comm: TWebsocketCommunicator;
  AResponse, Data: string;
begin
  Comm := TWebsocketCommunicator(Sender);
  Messages := TWebsocketMessageOwnerList.Create(True);
  try
    Comm.GetUnprocessedMessages(Messages);
    for m in Messages do
      if m is TWebsocketStringMessage then
      begin
        Data := TWebsocketStringMessage(m).Data;
        if assigned(FParent) and assigned(FParent.OnResponse) then
        begin
         FParent.OnResponse(self, Data, AResponse);
         Comm.WriteStringMessage(AResponse);
        end;
      end;
  finally
    Messages.Free;
  end;
end;

{ TMyWebSocketServer }
constructor TMyWebSocketServer.Create(const APort: integer);
begin
  inherited Create(False);
  FSocket := TWebSocketServer.Create(APort);
  FSocket.FreeHandlers := True;
  FSocket.RegisterHandler('*', '*', TSocketHandler.Create(self), True, True);
end;

destructor TMyWebSocketServer.Destroy;
begin
  FSocket.Stop;
  Terminate;
  WaitFor;
  FSocket.Free;
  inherited;
end;

procedure TMyWebSocketServer.Execute;
begin
  FSocket.Start;
end;
        
end`

Is my current code and it seem to be not only this issue here. It often raises a exception while closing the socket and I have a some leaks at the end.

**Comment by Warfley** [comment]
Hi, I was able to reproduce this now, and this seems to be a race condition. It looks like that when I call the `StopAccepting` method of the Socket, this takes a while until it takes effect, and the problem is that if Free gets called before this took effect (e.g. if the Free is called from another thread as the server is running in, as in this case), this results in access violations.

Free already calls Stop, so there is actually no need for you to call stop seperately when you want to free the server. I "fixed" this problem now by waiting in the Destructor for a small amount of time after close was called for the close to take effect.

This is currently only a "quick & dirty" fix, and I will think of something to do it correctly.

PS: about the memory leaks, they are probably the result that the mainthread terminates before the child thread was done cleaning up, at least that was the only way I could get them. In that case simply wait a bit before ending the main program
