### ISSUE TITLE
Utilize RecieveMessage 

### ISSUE THREAD

**Issue by hgbk** [Warfley/LazWebsockets#18]
In Readme.md is mentioned, that “RecieveMessage will block until a message was received. If the message was a binary or string message, it will be returned.” Does this mean that ReceiveMessage can be used instead of the GetUnprocessedMessage mechanism for string messages? If yes how can it be deployed / declared? An example like the Chat with ReceiveMessage would be very helpful.

**Comment by Warfley** [comment]
`ReceiveMessage` is weird and should only be used if you know it's behavior. What you are seeking is described in the following part of the README:

>If you are expecting a message and want to wait for it, you can use WaitForMessage, WaitForStringMessage, WaitForBinaryMessage or WaitForPongMessage. Unlike RecieveMessage, these function also return Pong messages, but also work in the asynchronous mode (when a reciever thread is running) as well as in the synchronous mode (i.e. calling recievethread itself). If any other messages arrived during this process, that are not the type of message you are waiting for, it will call the OnRecieveMessage event from within the current thread.

Example:
````
var
  client: TWebsocketClient;
  comm: TWebsocketCommunicator;
begin
  client := TWebsocketClient.Create('127.0.0.1', 8080);
  try
    comm := client.Connect(TSocketHandler.Create);
    try
      With comm.WaitForStringMessage do // recieve very first (string) message from server
      try
         WriteLn(Data); // Print out message
      finally
        Free; // Don't forget to free the Message instance recieved from WaitForStringMessage
      end;
    finally
      comm.Free;
    end;
  finally
    client.Free;
  end;
```

**Comment by hgbk** [comment]
Thank you for this! Now I understand, that the ReceiveMessage may work for specific client environments. In a server environment it's not really applicable because you normally don't know which connected client is sending next.
Once again thanks!!
