### ISSUE TITLE
Connect to a server with password and user

### ISSUE THREAD

**Issue by Blueicaro** [Warfley/LazWebsockets#21]
Hello, How can I handle a connectio to a server, using user and password?
/Jorge

**Comment by Warfley** [comment]
This depends on how the server implements authentification.
Generally speaking, you can simply add [custom headers](https://github.com/Warfley/LazWebsockets/blob/master/src/websocketsclient.pas#L45) to the HTTP request used to establish the websocket connection.

If the server uses [HTTP basic authentification](https://www.wikiwand.com/en/Basic_access_authentication) you can just set the authorization header.
If you have to get a token, e.g. via a cookie, you have to login first using normal webrequests and add the required headers then to the client request.

But there are endless possibilities, the server could make use of custom header fields or require the credentials to be encoded into the request path.

There is no one way  to do this, this completely depends on how the server is implemented

**Comment by Blueicaro** [comment]
Hello, I trying to connect with a robot ABB. Documentation says:
 User Authorization System (UAS). The Robot Web Services uses digest as the default authentication method, since it does not send the name and password in clear text. When an application connects and performs the first (unauthenticated) HTTP request, the HTTP server on the robot controller responds with a HTTP error "Unauthorized (401)". The requester must then send its credentials to be granted with a connection. When the connection is granted, the server also sends a cookie (ABBCX) to the client application. The ABBCX cookie is used by Robot Web Services to maintain a session (see section Session.). Client applications must use a HTTP client that supports digest authentication and can handle the cookies in order to access the Robot Web Services. The details are visible to the developer when using a browser or HTTP client library that supports digest 
Can you help me?
