### ISSUE TITLE
Is it possible to use descendant of TWebsocketCommunicator?

### ISSUE THREAD

**Issue by alpinistbg** [Warfley/LazWebsockets#23]
Hello,
I am wondering if it is possible to add a virtual method to the `TWebsocketHandler` to create the communicator object instead of creating it in `TWebsocketHandshakeHandler.PerformHandshake`?
Thus the `TWebsocketCommunicator` can be inherited to hold some additional data related to the connection, which can be extremely useful.

**Comment by Warfley** [comment]
Is now implemented
