### ISSUE TITLE
naming of classes, maybe improve?

### ISSUE THREAD

**Issue by Alexey-T** [Warfley/LazWebsockets#27]
post
https://forum.lazarus.freepascal.org/index.php/topic,48565.msg436924.html#msg436924
shows that code has 

- TWebsocketCommunicator
- TWebsocketMessage
- TWebsocketMessageOwnerList

and

- TWSConnection

why not TWebsocketConnection? maybe rename it to TWebsocketConnection and give an alias (FPC macro) for old short name.

**Comment by Warfley** [comment]
TWSConnection is a custom type created by that user and is not part of this library
