### ISSUE TITLE
How broadcast a message to all clients? 

### ISSUE THREAD

**Issue by fluisgirardi** [Warfley/LazWebsockets#5]
I'm studying your library, and I need, when certain events occur, a message informing all the clients about this.

So, how broadcast a message to all clients?

**Comment by Warfley** [comment]
Each connected client is represented by a `TWebsocketCommunincator` given to the `HandleCommunication` method of the registered `TWebsocketHandler`. So there are basically two methods:
1. Direct call:
In your `HandleCommunication` (or `DoHandleCommunication` when using the `TThreadedWebsocketHandler`) register the `TWebsocketCommunincator` in a list or something like that, and in it's `OnClose` event remove it from the list. Then to broadcast a message simply iterate that list and send the message to each client.
**BUT:** If the client is currently communicating fragmented messages, and you interrupt such a stream with your message, you will break the protocol and most likely the client will stop the connection immediatly. Either you don't send fragmented messages at all (which you should do for now anyway, as they are still broken). This can be ensured by setting the correct `MaxFrameLength` in `WriteMessage` to be large enough for your whole message. The other option is to do some locking to ensure your broadcast waits until no message stream is currently sent
2. Message Queue:
You have a List where you write all messages that should be broadcastet in, and the `TWebsocketHandler` frequently checks if messages are to be broadcastet and if so, sends them. This of course requires handling to delete messages that where sent by all clients, the number of clients who sent the message can be encoded in the message.
3. A mixture of both of them:
You could register a message queue for every client, and if you want to broadcast a message, simply iterate through all message queues (i.e. all clients) and add the message to each of them. The `TWebsocketHandler` then only needs to frequently check its own message queue, if messages are available take them out, and send them. This avoids the problem with fragmented messages from the first approach as well as the problem when to delete a message from the second (as there is one message per client)

In all cases you need a thread safe storage, which can created using the `TThreadedObject` class from `wsutils.pas`.

Here you have a simple example for the first approach (not tested, just simply written down, there can be any amount of typos in here):
```
type
  TClientList = class(specialize TFPGList<TWebsocketCommunicator>);
  TLockedClientList = class (specialize TThreadedObject<TClientList>);
  TSocketHandler = class(TThreadedWebsocketHandler)
  private
    FClients: TLockedClientList ;
    procedure ConnectionClosed(Sender: TObject);
    ...
  public
    constructor Create;
    destructor Destroy; override;
    procedure DoHandleCommunication(ACommunication: TWebsocketCommunincator);
      override;
    procedure BroadcastMessage(msg: String);
    ...
  end;

...
procedure TSocketHandler .ConnectionClosed(Sender: TObject);
var
  clients: TClientList;
begin
  clients := FClients.lock;
  try
    Clients.Remove(Sender as TWebsocketCommunicator);
  finally
    FClients.unlock;
  end;
  // Other stuff to do when the connection got closed
end;

constructor TSocketHandler.Create;
begin
  FClients := TLockedClientList.Create(TClientList.Create);
end;

destructor TSocketHandler.Destroy; 
begin
  FClients.Free;
end;

procedure TSocketHandler.DoHandleCommunication(ACommunication: TWebsocketCommunincator);
var
  clients: TClientList;
begin
  clients := FClients.lock;
  try
    Clients.Add(ACommunication);
  finally
    FClients.unlock;
  end;
  // Now here begins your communication
end;

procedure TSocketHandler.BroadcastMessage(msg: String);
var
  clients: TClientList;
  client: TWebsocketCommunicator;
begin
  clients := FClients.lock;
  try
    for c in clients do
      with c.WriteMessage(wmtString, msg.length) do
      begin
        WriteRaw(msg);
        Free;
      end;
  finally
    FClients.unlock;
  end;
end;
```

**Comment by Warfley** [comment]
Now part of TWebsocketHandler. See `broadcastServer` example for further information
