### ISSUE TITLE
Connect to WS server nodejs

### ISSUE THREAD

**Issue by esvignolo** [Warfley/LazWebsockets#7]
Hi... i have a issue connection to nodes

The connection (var conn) came = "Upgrade" 

I made a small fix in WebsocketsClient.pas :

  ResponseData.Headers.Parse(HeaderStr.TrimRight);
    if not ((ResponseData.StatusCode = 101)
      and ResponseData.Headers.TryGetData('Connection', conn)
      and ResponseData.Headers.TryGetData('Upgrade', upg)
      and ResponseData.Headers.TryGetData('Sec-WebSocket-Accept', respKey)
      and (**lowercase**(conn) = '**upgrade**') and (**lowercase**(upg) = 'websocket')
      and (respKey = ExpectedResponseKey)) then      

Thanks!

**Comment by Warfley** [comment]
Added this fix to the master branch.

Thank you
