### ISSUE TITLE
100% cpu load

### ISSUE THREAD

**Issue by ajvbun** [Warfley/LazWebsockets#9]
Hi,
thank you very much for writing this excellent utility, I think I will make good use of it.
However I found a small bug. After disconnecting the CPU load becomes 100%. Below you find my solution:

modify in unit wsutils .pas:

procedure TPoolableThread.Execute;
begin
  while not Self.Terminated do
  begin
    while isIdle do
    begin
      if Self.Terminated then
        Exit;
      TThread.Yield;
      sleep(0); 		//  <-- added to prevent 100% cpu load
    end;
    DoExecute;
    if FDoTerminate then
      self.Terminate
    else
      FIsIdle := True;
  end;
end;   

thanks, Anthony Vogelaar

**Comment by Warfley** [comment]
May I ask which OS/Architecture you are using? Because usually `Sleep(0)` and `TThread.Yield` should do pretty much the same, so it might be a bug in the underlying implementation of `TThread.Yield`.

That said, I replaced `TThread.Yield` with `Sleep(0)`, because as I said they should do the same, but if Yield doesn't work for you, I will switch it. Just pushed onto master

**Comment by ajvbun** [comment]
Dear Frederick,

thanks for your reply,

I use linux openSUSE  64 bit an I totally agree to replace TThread.Yield 
by Sleep (0).
In my application the websocket server should run in parallel of other 
tasks. One task of this application is processing incoming data from the 
webserver and providing a response, as in your chatserver example, but I 
also to send data to the webserver client independently.
My first step is to put the webserver into a thread separate from the 
main thread. At the moment I work on bi-directional thread communication.
This project is attached, you are free to use it as you like.
Thanks, you created a great solution.

Best regards, Anthony Vogelaar

=======================================

**Comment by Warfley** [comment]
I rewrote the thread pooling code, now this should not make any problems anymore. Also you can deactivate thread pooling if there are any other issues (see Readme for further information)
